language: python
python:
  - "3.6"
  - "3.7"
os:
  - linux
sudo: required
notifications:
  email: false
git:
  depth: 99999999
# TODO: remove these two settings after refactoring pipeline
env:
  - PYTHONHASHSEED=0

install:
  - sudo apt-get update -qq
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda install -y -c anaconda setuptools
  - conda update -q -y conda
  - conda info -a
  - conda create -c bioconda -c conda-forge -q -y -n test-environment python=$TRAVIS_PYTHON_VERSION coveralls
  - source activate test-environment
  - pip install -r requirements.txt
  - python -m nltk.downloader all
  
script: coverage run --source=lexmapr setup.py test

after_success:
  - coveralls
