language: python
python:
  - "3.6"
os:
  - linux
sudo: required
notifications:
  email: false
git:
  depth: 99999999
# TODO: remove these two settings after refactoring pipeline
env:
  - PYTHONHASHSEED=0

# See https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157

install:
  - sudo apt-get update -qq
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -q -y conda
  - conda info -a
  - conda create -c bioconda -c conda-forge -q -y -n test-environment python=$TRAVIS_PYTHON_VERSION coveralls
  - source activate test-environment
  - pip install -r requirements.txt
  - python -m nltk.downloader all
  
script: coverage run --source=lexmapr setup.py test

after_success:
  - coveralls
